// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID           int64
	UserID       uuid.UUID
	Amount       string
	Description  string
	Incoming     bool
	Type         string
	Recurring    bool
	StartDate    time.Time
	EndDate      time.Time
	Interval     sql.NullString
	DaysInterval sql.NullInt32
	Created      time.Time
	Updated      time.Time
}

type User struct {
	ID           uuid.UUID
	Provider     string
	ProviderID   string
	Username     string
	Email        string
	PasswordHash []byte
	Created      time.Time
	Updated      time.Time
}
