// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Budget struct {
	ID          string
	UserID      uuid.UUID
	Name        string
	Description string
	Amount      string
	StartDate   time.Time
	EndDate     time.Time
	Created     time.Time
	Updated     time.Time
}

type BudgetExpense struct {
	ID              int32
	BudgetID        string
	Name            string
	Description     string
	AllocatedAmount string
	CurrentAmount   string
}

type Transaction struct {
	ID           int32
	UserID       uuid.UUID
	Amount       string
	Description  string
	Type         string
	Recurring    bool
	StartDate    time.Time
	EndDate      time.Time
	Interval     sql.NullString
	DaysInterval sql.NullInt32
	Created      time.Time
	Updated      time.Time
}

type User struct {
	ID           uuid.UUID
	Provider     string
	ProviderID   string
	Username     string
	Email        string
	Avatar       sql.NullString
	PasswordHash []byte
	Created      time.Time
	Updated      time.Time
}
